# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
#permalink:        /:year/:month/:title
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ryan Lewis
tagline:          'Blog'
description:      'Ryan Lewis is a developer primarily working with .NET, Umbraco and other web technologies.'
url:              http://ryanl.me
baseurl:          /

author:
  name:           'Ryan Lewis'
  url:            https://twitter.com/wpyz

paginate:         5

# Custom vars
version:          2.1.0

twitter:
  profile:        https://twitter.com/wpyz

github:
  profile:        https://github.com/ryanlewis

sass:
  style:        :compressed
